language: python
python:
  - "3.6"
  - "3.7-dev"

before_install:
- pip install poetry
install:
- poetry install

before_script:
  - psql -c 'create database pollbot_test;' -U postgres
  - cp stickerfinder/travis_ultimate_pollbot.toml ~/.config/ultimate_pollbot.toml
script: poetry run pytest
